# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('loading.gif', '.'),
        ('te9wb-dqd91-001.ico', '.')
    ],
    hiddenimports=['pyembroidery.PngWriter', 'xml.etree', 'xml.etree.ElementTree', 'zlib'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'PIL',
        'cv2',
        'sklearn',
        'tensorflow',
        'torch',
        'jupyter',
        'IPython',
        'test',
        'unittest',
        'doctest',
        'pdb',
        'sqlite3',
        'email',
        'http',
        'multiprocessing',
        'concurrent',
        'distutils',
        'setuptools',
        'pkg_resources',
        'importlib_metadata',
        'zipp',
        'certifi',
        'charset_normalizer',
        'idna',
        'requests',
        'urllib3',
        'pip',
        'wheel',
        'typing_extensions',
        'packaging',
        'pyparsing'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Institch Embroidery Viewer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='te9wb-dqd91-001.ico',
    optimize=2
)